#!/usr/bin/expect -f
################################################################################
if { [llength $argv] != 4} {
    puts "usage: $argv0 ip port user passwd"
    exit 1
}

set ip   [lindex $argv 0] 
set port [lindex $argv 1]
set user [lindex $argv 2] 
set pwd  [lindex $argv 3]

spawn ssh -p $port -l $user $ip
expect {
    "(yes/no)" { send "yes\r"; exp_continue }
    "assword:" { send "$pwd\r"; }
}

interact
